apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-management-deployment
  labels:
    app: user-management
spec:
  replicas: 2  # Enable horizontal scaling
  selector:
    matchLabels:
      app: user-management
  template:
    metadata:
      labels:
        app: user-management
    spec:
      containers:
      - name: user-management
        image: axelfohlin/pa2567:user-management  # Replace with your Docker Hub image
        ports:
        - containerPort: 5000
        env:
        - name: DB_HOST
          value: "mysql-service"  # Internal service name
        - name: DB_USER
          value: "my_user"
        - name: DB_PASSWORD
          value: "my_password"
        - name: DB_NAME
          value: "movie_app"
