apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management
spec:
  selector:
    app: user-management
  ports:
  - protocol: TCP
    port: 5000        # Internal service port
    targetPort: 5000  # Matches containerPort in the deployment
  type: ClusterIP     # Internal access only (frontend will call this service)
