apiVersion: v1
kind: Service
metadata:
  name: user-management-service
  labels:
    app: user-management
spec:
  selector:
    app: user-management
  ports:
  - protocol: TCP
    port: 5000  # Port exposed by the service
    targetPort: 5000  # Port on the container
  type: ClusterIP  # Internal communication within the cluster
