apiVersion: v1
kind: Service
metadata:
  name: notification-service
  labels:
    app: notification
spec:
  selector:
    app: notification
  ports:
  - protocol: TCP
    port: 5000       # Exposed service port
    targetPort: 5000 # Port on the container
  type: ClusterIP
