FROM mysql:latest

# Set environment variables
ENV MYSQL_ROOT_PASSWORD=rootpassword
ENV MYSQL_DATABASE=my_database
ENV MYSQL_USER=my_user
ENV MYSQL_PASSWORD=my_password

# Copy initialization SQL scripts
# COPY init.sql /docker-entrypoint-initdb.d/

EXPOSE 3306
