apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
  labels:
    app: frontend
spec:
  replicas: 3  # Enable horizontal scaling
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
      - name: frontend
        image: axelfohlin/pa2567:frontend  # Replace with your Docker Hub image
        ports:
        - containerPort: 5001
        env:
        - name: USER_SERVICE_URL
          value: "http://user-management-service:5000"  # Internal URL for the backend
